package com.algotrader.domain.enums;

/**
 * Classifies the type of alert generated by the notification system.
 *
 * <p>Each alert type maps to a specific category of event that the trader
 * should be aware of. Used by {@code AlertSeverityRouter} to determine
 * which notification channels to use based on user preferences.
 */
public enum AlertType {

    /** Risk condition detected (margin, position limit, daily loss). */
    RISK,

    /** Order fully or partially filled. */
    ORDER_FILL,

    /** Order rejected by exchange or broker. */
    ORDER_REJECTION,

    /** Strategy lifecycle event (entry, exit, adjustment). */
    STRATEGY,

    /** Kite session lifecycle event (expired, reconnected). */
    SESSION,

    /** Position reconciliation mismatch detected. */
    RECONCILIATION,

    /** Kill switch activation. */
    KILL_SWITCH,

    /** System-level notification (startup, shutdown, health). */
    SYSTEM
}
