-- Baseline migration: captures the full schema as of 2026-02-12.
-- All 26 tables created by Hibernate ddl-auto=update are now under Flyway control.
-- Future schema changes MUST go through numbered migrations (V2__, V3__, etc.).

CREATE TABLE IF NOT EXISTS strategies (
    id VARCHAR(36) NOT NULL,
    closed_at TIMESTAMP(6),
    config JSON,
    created_at TIMESTAMP(6),
    deployed_at TIMESTAMP(6),
    description VARCHAR,
    expiry DATE,
    name VARCHAR(100),
    status VARCHAR(50),
    total_pnl NUMERIC(15, 2),
    trading_mode VARCHAR(10),
    type VARCHAR(50),
    underlying VARCHAR(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS strategy_legs (
    id VARCHAR(36) NOT NULL,
    option_type VARCHAR(10),
    position_id VARCHAR(36),
    quantity INTEGER NOT NULL,
    strategy_id VARCHAR(36),
    strike NUMERIC(10, 2),
    strike_selection JSON,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS strategy_runs (
    id VARCHAR(36) NOT NULL,
    adjustment_count INTEGER,
    created_at TIMESTAMP(6),
    entry_premium NUMERIC(15, 2),
    entry_time TIMESTAMP(6),
    exit_premium NUMERIC(15, 2),
    exit_reason VARCHAR(255),
    exit_time TIMESTAMP(6),
    gross_pnl NUMERIC(15, 2),
    leg_count INTEGER,
    net_pnl NUMERIC(15, 2),
    pnl_segments JSON,
    status VARCHAR(50),
    strategy_id VARCHAR(36),
    strategy_name VARCHAR(100),
    strategy_type VARCHAR(50),
    total_charges NUMERIC(15, 2),
    total_orders INTEGER,
    underlying VARCHAR(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS adjustment_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action_config JSON,
    adjustment_type VARCHAR(50),
    cooldown_minutes INTEGER,
    enabled BOOLEAN NOT NULL,
    last_triggered_at TIMESTAMP(6),
    max_triggers INTEGER,
    name VARCHAR(100),
    priority INTEGER NOT NULL,
    strategy_id VARCHAR(36),
    trigger_config JSON,
    trigger_count INTEGER,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(36) NOT NULL,
    amendment_reject_reason VARCHAR,
    amendment_status VARCHAR(50),
    average_fill_price NUMERIC(15, 2),
    broker_order_id VARCHAR(100),
    correlation_id VARCHAR(36),
    created_at TIMESTAMP(6),
    exchange VARCHAR(10),
    filled_quantity INTEGER,
    instrument_token BIGINT,
    order_type VARCHAR(10),
    parent_order_id VARCHAR(36),
    placed_at TIMESTAMP(6),
    price NUMERIC(15, 2),
    product VARCHAR(10),
    quantity INTEGER NOT NULL,
    rejection_reason VARCHAR,
    side VARCHAR(10),
    status VARCHAR(50),
    strategy_id VARCHAR(36),
    trading_symbol VARCHAR(50),
    trigger_price NUMERIC(15, 2),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS order_fills (
    id VARCHAR(36) NOT NULL,
    created_at TIMESTAMP(6),
    exchange_order_id VARCHAR(100),
    fees NUMERIC(10, 2),
    filled_at TIMESTAMP(6),
    instrument_token BIGINT,
    order_id VARCHAR(36),
    price NUMERIC(15, 2),
    quantity INTEGER NOT NULL,
    trading_symbol VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS positions (
    id VARCHAR(36) NOT NULL,
    average_price NUMERIC(15, 2),
    closed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    exchange VARCHAR(10),
    instrument_token BIGINT,
    last_price NUMERIC(15, 2),
    last_updated TIMESTAMP(6),
    m2m NUMERIC(15, 2),
    opened_at TIMESTAMP(6),
    overnight_quantity INTEGER,
    quantity INTEGER NOT NULL,
    realized_pnl NUMERIC(15, 2),
    strategy_id VARCHAR(36),
    trading_symbol VARCHAR(50),
    unrealized_pnl NUMERIC(15, 2),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS trades (
    id VARCHAR(36) NOT NULL,
    brokerage NUMERIC(10, 2),
    created_at TIMESTAMP(6),
    exchange VARCHAR(10),
    exchange_charges NUMERIC(10, 2),
    executed_at TIMESTAMP(6),
    gst NUMERIC(10, 2),
    instrument_token BIGINT,
    order_id VARCHAR(36),
    pnl NUMERIC(15, 2),
    price NUMERIC(15, 2),
    quantity INTEGER NOT NULL,
    sebi_charges NUMERIC(10, 2),
    side VARCHAR(10),
    stamp_duty NUMERIC(10, 2),
    strategy_id VARCHAR(36),
    stt NUMERIC(10, 2),
    total_charges NUMERIC(10, 2),
    trading_symbol VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6),
    download_date DATE,
    exchange VARCHAR(10),
    expiry DATE,
    instrument_type VARCHAR(10),
    lot_size INTEGER,
    name VARCHAR(100),
    segment VARCHAR(20),
    strike NUMERIC(10, 2),
    tick_size NUMERIC(10, 4),
    token BIGINT,
    trading_symbol VARCHAR(50),
    underlying VARCHAR(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS daily_pnl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6),
    date DATE,
    losing_trades INTEGER,
    max_drawdown NUMERIC(15, 2),
    realized_pnl NUMERIC(15, 2),
    total_trades INTEGER,
    unrealized_pnl NUMERIC(15, 2),
    winning_trades INTEGER,
    PRIMARY KEY (id),
    CONSTRAINT ukb5ilrs2545ftj33sjp4lcomck UNIQUE (date)
);

CREATE TABLE IF NOT EXISTS kite_session (
    id VARCHAR(36) NOT NULL,
    access_token VARCHAR(255),
    created_at TIMESTAMP(6),
    expires_at TIMESTAMP(6),
    login_time TIMESTAMP(6),
    user_id VARCHAR(36),
    user_name VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action VARCHAR(50),
    context_json JSON,
    entity_id VARCHAR(36),
    entity_type VARCHAR(50),
    event_type VARCHAR(50),
    ip_address VARCHAR(45),
    new_value JSON,
    old_value JSON,
    timestamp TIMESTAMP(6),
    user_id VARCHAR(36),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS decision_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_context VARCHAR,
    decision_type VARCHAR(100) NOT NULL,
    outcome VARCHAR(50) NOT NULL,
    reasoning VARCHAR NOT NULL,
    session_date DATE,
    severity VARCHAR(50),
    source VARCHAR(50) NOT NULL,
    source_id VARCHAR(100),
    timestamp TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS execution_journal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    broker_order_id VARCHAR(100),
    created_at TIMESTAMP(6),
    execution_group_id VARCHAR(36),
    failure_reason VARCHAR,
    instrument_token BIGINT,
    leg_index INTEGER,
    operation_type VARCHAR(50),
    quantity INTEGER NOT NULL,
    side VARCHAR(10),
    status VARCHAR(50),
    strategy_id VARCHAR(36),
    total_legs INTEGER,
    trading_symbol VARCHAR(50),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS morph_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    child_strategy_id VARCHAR(36),
    child_strategy_type VARCHAR(50),
    morph_reason VARCHAR,
    morphed_at TIMESTAMP(6),
    parent_pnl_at_morph NUMERIC(15, 2),
    parent_strategy_id VARCHAR(36) NOT NULL,
    parent_strategy_type VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS morph_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    error_message VARCHAR,
    executed_at TIMESTAMP(6),
    plan_details VARCHAR,
    reason VARCHAR,
    source_strategy_id VARCHAR(36) NOT NULL,
    source_strategy_type VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    target_types VARCHAR,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dead_letter_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6),
    error_message VARCHAR,
    event_type VARCHAR(100),
    last_retry_at TIMESTAMP(6),
    max_retries INTEGER,
    payload JSON,
    resolved_at TIMESTAMP(6),
    retry_count INTEGER,
    stack_trace VARCHAR,
    status VARCHAR(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS risk_limit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    changed_by VARCHAR(100),
    limit_name VARCHAR(100),
    limit_type VARCHAR(50),
    new_value VARCHAR(100),
    old_value VARCHAR(100),
    reason VARCHAR,
    timestamp TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    alert_type VARCHAR(50),
    created_at TIMESTAMP(6),
    enabled BOOLEAN NOT NULL,
    enabled_channels VARCHAR(100),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tick_recordings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6),
    instrument_token BIGINT,
    recorded_at TIMESTAMP(6),
    tick_data JSON,
    trading_symbol VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS trade_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6),
    market_condition VARCHAR(50),
    note VARCHAR,
    run_id VARCHAR(36),
    star_rating INTEGER,
    strategy_id VARCHAR(36),
    tags VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS condition_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    cooldown_minutes INTEGER,
    created_at TIMESTAMP(6),
    description VARCHAR,
    evaluation_mode VARCHAR(50) NOT NULL,
    indicator_field VARCHAR(255),
    indicator_period INTEGER,
    indicator_type VARCHAR(50) NOT NULL,
    instrument_token BIGINT NOT NULL,
    last_triggered_at TIMESTAMP(6),
    max_triggers INTEGER,
    name VARCHAR(255) NOT NULL,
    operator VARCHAR(50) NOT NULL,
    secondary_threshold NUMERIC(38, 2),
    status VARCHAR(50) NOT NULL,
    strategy_config JSON,
    strategy_type VARCHAR(50),
    threshold_value NUMERIC(38, 2) NOT NULL,
    trading_symbol VARCHAR(255) NOT NULL,
    trigger_count INTEGER,
    underlying VARCHAR(255),
    updated_at TIMESTAMP(6),
    valid_from TIME(0),
    valid_until TIME(0),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS composite_condition_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6),
    description VARCHAR,
    logic_operator VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    strategy_config JSON,
    strategy_type VARCHAR(50),
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS composite_rule_children (
    composite_rule_id BIGINT NOT NULL,
    child_rule_id BIGINT,
    CONSTRAINT fkir7ja9fy0t83skmx5xx21yecc FOREIGN KEY (composite_rule_id) REFERENCES composite_condition_rules (id)
);

CREATE TABLE IF NOT EXISTS condition_trigger_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action_taken VARCHAR(50),
    indicator_type VARCHAR(50),
    indicator_value NUMERIC(38, 2),
    operator VARCHAR(50),
    rule_id BIGINT NOT NULL,
    rule_name VARCHAR(255),
    strategy_id VARCHAR(255),
    threshold_value NUMERIC(38, 2),
    triggered_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS watchlist_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP(6),
    enabled BOOLEAN NOT NULL,
    expiry_type VARCHAR(50) NOT NULL,
    strikes_from_atm INTEGER NOT NULL,
    underlying VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP(6),
    PRIMARY KEY (id)
);
